export const doctors = [
    {
        "_id": { "$oid": "66b08cccdb498e39c579b90a" },
        "id": 1,
        "title": "Dr.Srinivasan",
        "description": "Senior Cardiologist with 15 years of experience specializing in heart disease prevention and treatment.",
        "specialization": "Cardiology",
        "consultation_fee": 500,
        "image": "https://i.pinimg.com/736x/bb/ef/69/bbef6907a1fc7de46cb20daa53f7dce4.jpg",
        "rating": { "rate": 4.8, "count": 200 },
        "__v": 0
    },
    {
        "_id": { "$oid": "66b08cccdb498e39c579b90b" },
        "id": 2,
        "title": "Dr.Guruprasath",
        "description": "Experienced Neurologist specializing in brain and nervous system disorders, with over a decade of practice.",
        "specialization": "Neurology",
        "consultation_fee": 700,
        "image": "https://i.pinimg.com/736x/6d/b4/4f/6db44f206bb332cd749c5e92ed9bfa91.jpg",
        "rating": { "rate": 4.7, "count": 180 },
        "__v": 0
    },
    {
        "_id": { "$oid": "66b08cccdb498e39c579b90c" },
        "id": 3,
        "title": "Dr.DineshKumar",
        "description": "Renowned Orthopedic Surgeon specializing in joint replacement and sports injuries.",
        "specialization": "Orthopedics",
        "consultation_fee": 600,
        "image": "https://i.pinimg.com/736x/fc/65/ec/fc65ec45928e9dc0d1e16be43ae988e4.jpg",
        "rating": { "rate": 4.9, "count": 250 },
        "__v": 0
    },
    {
        "_id": { "$oid": "66b08cccdb498e39c579b90d" },
        "id": 4,
        "title": "Dr.Saravanan",
        "description": "Dermatologist with expertise in skin diseases, cosmetic treatments, and laser therapies.",
        "specialization": "Dermatology",
        "consultation_fee": 550,
        "image": "https://i.pinimg.com/736x/39/ed/cf/39edcfabc9ce33fa8680806c8aa5a91d.jpg",
        "rating": { "rate": 4.6, "count": 170 },
        "__v": 0
        },
        {
            "_id": { "$oid": "66b08cccdb498e39c579b919" },
            "id": 5,
            "title": "Dr.Ajay Mehta",
            "description": "Hematologist specializing in blood disorders and transfusion medicine.",
            "specialization": "Hematology",
            "consultation_fee": 700,
            "image": "https://i.pinimg.com/736x/c1/e2/bd/c1e2bda65737aee4c0a9c0058aa3f112.jpg",
            "rating": { "rate": 4.9, "count": 230 },
            "__v": 0
        },
        {
            "_id": { "$oid": "66b08cccdb498e39c579b91a" },
            "id": 6,
            "title": "Dr.Swati Agarwal",
            "description": "Pediatrician specializing in child health, vaccinations, and growth disorders.",
            "specialization": "Pediatrics",
            "consultation_fee": 500,
            "image": "https://i.pinimg.com/736x/bb/74/ba/bb74bae0879782206e5970e65efcfaa6.jpg",
            "rating": { "rate": 4.8, "count": 220 },
            "__v": 0
        },
        {
            "_id": { "$oid": "66b08cccdb498e39c579b91b" },
            "id": 7,
            "title": "Dr.Vikram Singh",
            "description": "Urologist specializing in kidney stones, prostate health, and urinary tract disorders.",
            "specialization": "Urology",
            "consultation_fee": 650,
            "image": "https://i.pinimg.com/736x/08/68/fe/0868fe0425b9f9de09729bcbaf6b60da.jpg",
            "rating": { "rate": 4.7, "count": 200 },
            "__v": 0
        },
        {
            "_id": { "$oid": "66b08cccdb498e39c579b91c" },
            "id": 8,
            "title": "Dr.Manjula Reddy",
            "description": "Gastroenterologist specializing in digestive system disorders and liver diseases.",
            "specialization": "Gastroenterology",
            "consultation_fee": 720,
            "image": "https://i.pinimg.com/736x/c9/e0/b5/c9e0b5e45aad1de8e27b25ec6ce3cd27.jpg",
            "rating": { "rate": 4.9, "count": 245 },
            "__v": 0
        },
        {
            "_id": { "$oid": "66b08cccdb498e39c579b91d" },
            "id": 9,
            "title": "Dr.Rahul Desai",
            "description": "Ophthalmologist specializing in eye disorders, laser treatments, and cataract surgery.",
            "specialization": "Ophthalmology",
            "consultation_fee": 580,
            "image": "https://i.pinimg.com/736x/8b/92/c8/8b92c83a0c5a9161ccbe91331549255c.jpg",
            "rating": { "rate": 4.8, "count": 210 },
            "__v": 0
        },
        {
            "_id": { "$oid": "66b08cccdb498e39c579b91b" },
            "id": 10,
            "title": "Dr.Vikram",
            "description": "Urologist specializing in kidney stones, prostate health, and urinary tract disorders.",
            "specialization": "Urology",
            "consultation_fee": 650,
            "image": "https://i.pinimg.com/736x/n4/o5/p6/n4o5p6q7r8s9t0u1v2w3.jpg",
            "rating": { "rate": 4.7, "count": 200 },
            "__v": 0
        },
        {
            "_id": { "$oid": "66b08cccdb498e39c579b91c" },
            "id": 11,
            "title": "Dr.Mano Reddy",
            "description": "Gastroenterologist specializing in digestive system disorders and liver diseases.",
            "specialization": "Gastroenterology",
            "consultation_fee": 720,
            "image": "https://i.pinimg.com/736x/da/0d/42/da0d42891be44d43225b32c9dfbcaf53.jpg",
            "rating": { "rate": 4.9, "count": 245 },
            "__v": 0
        },
        {
            "_id": { "$oid": "66b08cccdb498e39c579b91d" },
            "id": 12,
            "title": "Dr.Pawan",
            "description": "Ophthalmologist specializing in eye disorders, laser treatments, and cataract surgery.",
            "specialization": "Ophthalmology",
            "consultation_fee": 580,
            "image": "https://i.pinimg.com/736x/da/0d/42/da0d42891be44d43225b32c9dfbcaf53.jpg",
            "rating": { "rate": 4.8, "count": 210 },
            "__v": 0
        },
        {
            "_id": { "$oid": "66b08cccdb498e39c579b91b" },
            "id": 13,
            "title": "Dr.Amit Singh",
            "description": "Urologist specializing in kidney stones, prostate health, and urinary tract disorders.",
            "specialization": "Urology",
            "consultation_fee": 650,
            "image": "https://i.pinimg.com/736x/4e/7a/9c/4e7a9c2b6fd4d122adabae654e711c20.jpg",
            "rating": { "rate": 4.7, "count": 200 },
            "__v": 0
        },
        {
            "_id": { "$oid": "66b08cccdb498e39c579b91c" },
            "id": 14,
            "title": "Dr.Sudhakar Reddy",
            "description": "Gastroenterologist specializing in digestive system disorders and liver diseases.",
            "specialization": "Gastroenterology",
            "consultation_fee": 720,
            "image": "https://i.pinimg.com/736x/0b/f0/f8/0bf0f84b7e1e3792159c721ee53595df.jpg",
            "rating": { "rate": 4.9, "count": 245 },
            "__v": 0
        },
        {
            "_id": { "$oid": "66b08cccdb498e39c579b91d" },
            "id": 15,
            "title": "Dr.Ram Moorthy",
            "description": "Ophthalmologist specializing in eye disorders, laser treatments, and cataract surgery.",
            "specialization": "Ophthalmology",
            "consultation_fee": 580,
            "image": "https://i.pinimg.com/736x/80/82/6a/80826aaeaa9a545882418a78597f6d9e.jpg",
            "rating": { "rate": 4.8, "count": 210 },
            "__v": 0
        },
        {
            "_id": { "$oid": "66b08cccdb498e39c579b91b" },
            "id": 16,
            "title": "Dr.Vignesh",
            "description": "Urologist specializing in kidney stones, prostate health, and urinary tract disorders.",
            "specialization": "Urology",
            "consultation_fee": 650,
            "image": "https://i.pinimg.com/736x/6c/6e/d7/6c6ed7f4011b7f926b3f1505475aba16.jpg",
            "rating": { "rate": 4.7, "count": 200 },
            "__v": 0
        },
        {
            "_id": { "$oid": "66b08cccdb498e39c579b91c" },
            "id": 17,
            "title": "Dr.Dhanushwaran",
            "description": "Gastroenterologist specializing in digestive system disorders and liver diseases.",
            "specialization": "Gastroenterology",
            "consultation_fee": 720,
            "image": "https://i.pinimg.com/736x/fb/77/65/fb77654d59270afdda012a1b0fc7a09f.jpg",
            "rating": { "rate": 4.9, "count": 245 },
            "__v": 0
        },
        {
            "_id": { "$oid": "66b08cccdb498e39c579b91d" },
            "id": 18,
            "title": "Dr.Rajagopal",
            "description": "Ophthalmologist specializing in eye disorders, laser treatments, and cataract surgery.",
            "specialization": "Ophthalmology",
            "consultation_fee": 580,
            "image": "https://i.pinimg.com/736x/e0/99/f6/e099f6ba0a5d290b992bf04cc4b08d57.jpg",
            "rating": { "rate": 4.8, "count": 210 },
            "__v": 0
        }, 
        {
            "_id": { "$oid": "66b08cccdb498e39c579b91b" },
            "id": 19,
            "title": "Dr.ChandraMohan",
            "description": "Urologist specializing in kidney stones, prostate health, and urinary tract disorders.",
            "specialization": "Urology",
            "consultation_fee": 650,
            "image": "https://i.pinimg.com/736x/0b/f0/f8/0bf0f84b7e1e3792159c721ee53595df.jpg",
            "rating": { "rate": 4.7, "count": 200 },
            "__v": 0
        },
        {
            "_id": { "$oid": "66b08cccdb498e39c579b91c" },
            "id": 20,
            "title": "Dr.Abinav",
            "description": "Gastroenterologist specializing in digestive system disorders and liver diseases.",
            "specialization": "Gastroenterology",
            "consultation_fee": 720,
            "image": "https://i.pinimg.com/736x/5a/d5/8c/5ad58c1935e8f3a588a68261280ec57b.jpg",
            "rating": { "rate": 4.9, "count": 245 },
            "__v": 0
        },
        {
            "_id": { "$oid": "66b08cccdb498e39c579b91d" },
            "id": 21,
            "title": "Dr.Ganesh Chowdry",
            "description": "Ophthalmologist specializing in eye disorders, laser treatments, and cataract surgery.",
            "specialization": "Ophthalmology",
            "consultation_fee": 580,
            "image": "https://i.pinimg.com/736x/da/0d/42/da0d42891be44d43225b32c9dfbcaf53.jpg",
            "rating": { "rate": 4.8, "count": 210 },
            "__v": 0
        }
]